server:
    - listen_ip: 127.0.0.1
    - port: 8000
    - log_level: INFO
routes:
    - location: /emdr
      handler: web
      fs_path: /Users/mmuthanna/git/experiments/emdr
    - location: /hype
      handler: file
      fs_path: /Users/mmuthanna/git/hype
