listen_ip: localhost
port: 4000
log_level: info
enable_tls: false
tls_cert_file: localhost.crt
tls_key_file: localhost.key
routes:
    - location: /lb
      backends:
          - host: google.com
            port: 80
          - host: yahoo.com
            port: 80
          - host: bing.com
            port: 80
    - location: /lb2
      backends:
          - host: reddit.com
            port: 80
          - host: news.ycombinator.com
            port: 80
          - host: amazon.com
            port: 80
    - location: /google
      host_header: google.com
      backends:
          - host: google.com
            port: 443
            enable_tls: true
    - location: /yahoo
      host_header: yahoo.com
      backends:
          - host: yahoo.com
            port: 443
            enable_tls: true
    - location: /pitchy
      host_header: pitchy.ninja
      backends:
          - host: pitchy.ninja
            port: 443
            enable_tls: true
