listen_ip: 127.0.0.1
port: 4000
log_level: Info
routes:
    - location: /lb
      backends:
          - host: google.com
            port: 80
          - host: yahoo.com
            port: 80
          - host: bing.com
            port: 80
    - location: /lb2
      backends:
          - host: reddit.com
            port: 80
          - host: news.ycombinator.com
            port: 80
          - host: amazon.com
            port: 80
